// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoltcond10oblique provides the "lmmonoltcond10 oblique" TrueType font
// from the Latin Modern font family.
package lmmonoltcond10oblique // import "github.com/go-fonts/latin-modern/lmmonoltcond10oblique"

import _ "embed"

// TTF is the data for the "lmmonoltcond10 oblique" TrueType font.
//
//go:embed lmmonoltcond10-oblique.otf
var TTF []byte
