// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmromandemi10oblique provides the "lmromandemi10 oblique" TrueType font
// from the Latin Modern font family.
package lmromandemi10oblique // import "github.com/go-fonts/latin-modern/lmromandemi10oblique"

import _ "embed"

// TTF is the data for the "lmromandemi10 oblique" TrueType font.
//
//go:embed lmromandemi10-oblique.otf
var TTF []byte
