// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonocaps10oblique provides the "lmmonocaps10 oblique" TrueType font
// from the Latin Modern font family.
package lmmonocaps10oblique // import "github.com/go-fonts/latin-modern/lmmonocaps10oblique"

import _ "embed"

// TTF is the data for the "lmmonocaps10 oblique" TrueType font.
//
//go:embed lmmonocaps10-oblique.otf
var TTF []byte
