// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoproplt10regular provides the "lmmonoproplt10 regular" TrueType font
// from the Latin Modern font family.
package lmmonoproplt10regular // import "github.com/go-fonts/latin-modern/lmmonoproplt10regular"

import _ "embed"

// TTF is the data for the "lmmonoproplt10 regular" TrueType font.
//
//go:embed lmmonoproplt10-regular.otf
var TTF []byte
