// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonolt10regular provides the "lmmonolt10 regular" TrueType font
// from the Latin Modern font family.
package lmmonolt10regular // import "github.com/go-fonts/latin-modern/lmmonolt10regular"

import _ "embed"

// TTF is the data for the "lmmonolt10 regular" TrueType font.
//
//go:embed lmmonolt10-regular.otf
var TTF []byte
