// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoproplt10oblique provides the "lmmonoproplt10 oblique" TrueType font
// from the Latin Modern font family.
package lmmonoproplt10oblique // import "github.com/go-fonts/latin-modern/lmmonoproplt10oblique"

import _ "embed"

// TTF is the data for the "lmmonoproplt10 oblique" TrueType font.
//
//go:embed lmmonoproplt10-oblique.otf
var TTF []byte
