// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmromandunh10oblique provides the "lmromandunh10 oblique" TrueType font
// from the Latin Modern font family.
package lmromandunh10oblique // import "github.com/go-fonts/latin-modern/lmromandunh10oblique"

import _ "embed"

// TTF is the data for the "lmromandunh10 oblique" TrueType font.
//
//go:embed lmromandunh10-oblique.otf
var TTF []byte
