// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoprop10oblique provides the "lmmonoprop10 oblique" TrueType font
// from the Latin Modern font family.
package lmmonoprop10oblique // import "github.com/go-fonts/latin-modern/lmmonoprop10oblique"

import _ "embed"

// TTF is the data for the "lmmonoprop10 oblique" TrueType font.
//
//go:embed lmmonoprop10-oblique.otf
var TTF []byte
