// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoprop10regular provides the "lmmonoprop10 regular" TrueType font
// from the Latin Modern font family.
package lmmonoprop10regular // import "github.com/go-fonts/latin-modern/lmmonoprop10regular"

import _ "embed"

// TTF is the data for the "lmmonoprop10 regular" TrueType font.
//
//go:embed lmmonoprop10-regular.otf
var TTF []byte
