// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonolt10boldoblique provides the "lmmonolt10 boldoblique" TrueType font
// from the Latin Modern font family.
package lmmonolt10boldoblique // import "github.com/go-fonts/latin-modern/lmmonolt10boldoblique"

import _ "embed"

// TTF is the data for the "lmmonolt10 boldoblique" TrueType font.
//
//go:embed lmmonolt10-boldoblique.otf
var TTF []byte
