// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmsansquot8bold provides the "lmsansquot8 bold" TrueType font
// from the Latin Modern font family.
package lmsansquot8bold // import "github.com/go-fonts/latin-modern/lmsansquot8bold"

import _ "embed"

// TTF is the data for the "lmsansquot8 bold" TrueType font.
//
//go:embed lmsansquot8-bold.otf
var TTF []byte
