// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmsans10boldoblique provides the "lmsans10 boldoblique" TrueType font
// from the Latin Modern font family.
package lmsans10boldoblique // import "github.com/go-fonts/latin-modern/lmsans10boldoblique"

import _ "embed"

// TTF is the data for the "lmsans10 boldoblique" TrueType font.
//
//go:embed lmsans10-boldoblique.otf
var TTF []byte
