// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoltcond10regular provides the "lmmonoltcond10 regular" TrueType font
// from the Latin Modern font family.
package lmmonoltcond10regular // import "github.com/go-fonts/latin-modern/lmmonoltcond10regular"

import _ "embed"

// TTF is the data for the "lmmonoltcond10 regular" TrueType font.
//
//go:embed lmmonoltcond10-regular.otf
var TTF []byte
