// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmsansdemicond10oblique provides the "lmsansdemicond10 oblique" TrueType font
// from the Latin Modern font family.
package lmsansdemicond10oblique // import "github.com/go-fonts/latin-modern/lmsansdemicond10oblique"

import _ "embed"

// TTF is the data for the "lmsansdemicond10 oblique" TrueType font.
//
//go:embed lmsansdemicond10-oblique.otf
var TTF []byte
