// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoproplt10bold provides the "lmmonoproplt10 bold" TrueType font
// from the Latin Modern font family.
package lmmonoproplt10bold // import "github.com/go-fonts/latin-modern/lmmonoproplt10bold"

import _ "embed"

// TTF is the data for the "lmmonoproplt10 bold" TrueType font.
//
//go:embed lmmonoproplt10-bold.otf
var TTF []byte
