// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonolt10oblique provides the "lmmonolt10 oblique" TrueType font
// from the Latin Modern font family.
package lmmonolt10oblique // import "github.com/go-fonts/latin-modern/lmmonolt10oblique"

import _ "embed"

// TTF is the data for the "lmmonolt10 oblique" TrueType font.
//
//go:embed lmmonolt10-oblique.otf
var TTF []byte
