// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonoproplt10boldoblique provides the "lmmonoproplt10 boldoblique" TrueType font
// from the Latin Modern font family.
package lmmonoproplt10boldoblique // import "github.com/go-fonts/latin-modern/lmmonoproplt10boldoblique"

import _ "embed"

// TTF is the data for the "lmmonoproplt10 boldoblique" TrueType font.
//
//go:embed lmmonoproplt10-boldoblique.otf
var TTF []byte
