// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmromandemi10regular provides the "lmromandemi10 regular" TrueType font
// from the Latin Modern font family.
package lmromandemi10regular // import "github.com/go-fonts/latin-modern/lmromandemi10regular"

import _ "embed"

// TTF is the data for the "lmromandemi10 regular" TrueType font.
//
//go:embed lmromandemi10-regular.otf
var TTF []byte
