// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmsansquot8boldoblique provides the "lmsansquot8 boldoblique" TrueType font
// from the Latin Modern font family.
package lmsansquot8boldoblique // import "github.com/go-fonts/latin-modern/lmsansquot8boldoblique"

import _ "embed"

// TTF is the data for the "lmsansquot8 boldoblique" TrueType font.
//
//go:embed lmsansquot8-boldoblique.otf
var TTF []byte
