// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmonolt10bold provides the "lmmonolt10 bold" TrueType font
// from the Latin Modern font family.
package lmmonolt10bold // import "github.com/go-fonts/latin-modern/lmmonolt10bold"

import _ "embed"

// TTF is the data for the "lmmonolt10 bold" TrueType font.
//
//go:embed lmmonolt10-bold.otf
var TTF []byte
