// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmromancaps10oblique provides the "lmromancaps10 oblique" TrueType font
// from the Latin Modern font family.
package lmromancaps10oblique // import "github.com/go-fonts/latin-modern/lmromancaps10oblique"

import _ "embed"

// TTF is the data for the "lmromancaps10 oblique" TrueType font.
//
//go:embed lmromancaps10-oblique.otf
var TTF []byte
